In [3]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

# 1

In [4]:
mri = cv2.imread('MRI.jpg', cv2.IMREAD_GRAYSCALE)
mri2 = cv2.imread('MRI2.jpg', cv2.IMREAD_GRAYSCALE)

## a

In [ ]:
points = []

# Mouse callback function
def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        # Save the coordinate
        points.append([x, y])
        # This draws a small red circle where you clicked
        cv2.circle(img, (x, y), 5, (0, 0, 255), -1)
        cv2.imshow('win', img)
        print(f"Point captured: ({x}, {y})")

# Source first, then Target
image_files = [mri2, mri]
all_points = []

for img in image_files:
    # Reset points list for the current image
    points = []
    cv2.namedWindow('win', cv2.WINDOW_NORMAL)
    cv2.imshow('win', img)
    
    # Link the mouse click to the window
    cv2.setMouseCallback('win', click_event)

    print(f"Click 3 corresponding points on {img}...")
    
    # Wait until 3 points are clicked
    while True:
        k = cv2.waitKey(1) & 0xFF
        if len(points) == 3:
            print(f"3 points selected for {img}. Press any key to continue...")
            cv2.waitKey(0) # Wait for a key press to confirm and move on
            break
        if k == 27: # Allow exiting with esc key
            break
            
    # Saves these 3 points to the main list
    all_points.append(points)
    cv2.destroyAllWindows()

# Convert to numpy float32 format for Affine 
src_points = np.float32(all_points[0]) # From source
dst_points = np.float32(all_points[1]) # From target

# calculating the matrix automatically
affine_matrix = cv2.getAffineTransform(src_points, dst_points)
print("\nCalculated Affine Matrix:")
print(affine_matrix)

Click 3 corresponding points on [[ 9 10 10 ...  6  7  6]
 [ 4 12 18 ...  2  9  4]
 [13 19 11 ...  5 12  6]
 ...
 [10 11  6 ... 23 17  3]
 [17 11  8 ...  9 13 17]
 [12  7 10 ...  6  9 11]]...


## b